version: "3"

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile  
    container_name: nginx
    image: nginx:latest
    restart: always
    ports:
      - "8080:80"
      - "9001:9001"
    networks:
      - nginx-network
    depends_on:
      - app

  app:
    build:
      context: ../assigment-2
      dockerfile: Dockerfile
    image: app:latest
    container_name: app
    restart: always
    networks:
      - nginx-network
    
networks:
  nginx-network:
    driver: bridge
